### ISSUE TITLE
com.inet.lib.less.LessException: Unexpected end of Less data

### ISSUE THREAD

**Issue by frangarcia** [i-net-software/jlessc#10]
I am not quite sure the fix for the issue #9 fixed this, but with the less file https://gist.github.com/frangarcia/d5904f54a911b3b74d2d I am also having the same exception as before. 

Not quite sure either the fix has already been deployed properly to maven repositories.

**Comment by Horcrux7** [comment]
The fix is of course only in the source code repository. A new version need some time. If you want try it you need to build it self.

**Comment by frangarcia** [comment]
Do you know when are you going to be able to release those changes? Let me know also if I can help you to speed the process.

**Comment by Horcrux7** [comment]
Do you have test the fix? Does it work for you now?

I think it will take some weeks. I want implement some missing features before.

**Comment by frangarcia** [comment]
Yes, I tested the fix and it worked, but I am also having problems with bigger less files for which the script never ends. I will try to send you an example for any of these files asap.

**Comment by Horcrux7** [comment]
Do you have any news over the example?

**Comment by frangarcia** [comment]
I am afraid I haven't found any example I can send you as the less file I found the problem is being used in production and I cannot forward it to you. I will try this week to find a shorter version with the problem.

**Comment by frangarcia** [comment]
Hi, I think I have been able to find a ultra-reduced less file for which the less compiler does not end ever.

@defaultFontSize        : 14;
@context-px-size: 10;

.font-size(@target-px-size, @context-px-size: @context-px-size) {
  .rem(@target-px-size, @context-px-size);
  font-size: 14px;
}

.rem(@target-px-size; @context-px-size: @context-px-size) {
  @toPx: 14px;
}

body {
  .font-size(@defaultFontSize);
}

I hope it helps!

**Comment by Horcrux7** [comment]
Thanks for the test case. I have fix the loop. Please try it.

**Comment by frangarcia** [comment]
Looking good the endless loop. I have just found another problem with this example:

@customFonts: none;

.box-sizing(...) {
@process: ~`(function(e){return e=e||"content-box"})((function(){var e="@{arguments}";return e=e.replace(/^\[|\]$/g,"")})())`;
-webkit-box-sizing: @process;
-moz-box-sizing: @process;
box-sizing: @process;
}

.importCustomFonts when not (@customFonts = none) {
.for(@customFonts); .-each(@customFont) {
.custom-font(@customFont, @themeBasePath)
}
}
.importCustomFonts;
*, *:before, *:after {
.box-sizing(border-box);
}

It is working fine with other compilers.

**Comment by frangarcia** [comment]
Another issue with this example:

.box-shadow(...) {
@process: ~`(function(e){e=e||"0";var t=/\d/gi,r=/(?:\s|^)(\.?\d+\.?\d*)(?![^(]*\)|\w|%|\.)/gi;return/^[^, ]*,/.test(e)&&(e=e.replace(/(?:,)(?![^(]*\))/g,"")),t.test(e)&&(e=e.replace(r,function(e){return 0==e&&e||e+"px"})),e})((function(){var e="@{arguments}";return e=e.replace(/^\[|\]$/g,"")})())`;
-webkit-box-shadow: @process;
-moz-box-shadow: @process;
box-shadow: @process;
}

.xOverlayInner {
.box-shadow(#999 2px 2px 10px 0px);
}

**Comment by Horcrux7** [comment]
FYI. Thanks for the samples. I can reproduce some problems. I working on it. Some more complex tests show more problems. That it will take some time.

**Comment by Horcrux7** [comment]
Hi Fran, 

I have fixed your both error samples. I hope this was the last problem. 
I have a question. Do you have write this less self or do you use a framework? Which?

Volker

**Comment by frangarcia** [comment]
Hi, that is working fine and I have already passed the full less file with no errors. We will be checking the output in the next few days. We write the less files ourselves but we use the framework http://lesshat.madebysource.com/ to use some mixins. Thanks!

**Comment by Horcrux7** [comment]
I have release Version 1.2. If you find a new problem then open a new ticket.
