### ISSUE TITLE
@import does not work - No such file or directory

### ISSUE THREAD

**Issue by woutersamaey** [i-net-software/jlessc#11]
In my LESS file i have this line:

@import 'shared/all.less';

JLessC goes ahead and tries to load the file /path/to/file/'shared/all.less' with the single quotes still attached.

Obviously this doesn't work.

Sounds like a simple thing to fix, but I don't know here to start. Can you make the program ignore the single quotes?

Double quotes work fine.

Thanks

**Comment by Horcrux7** [comment]
Which version do you use? This work for me.

**Comment by woutersamaey** [comment]
Hi Volker,

I have put this in my pom.xml:

<dependencies>
    <dependency>
  <groupId>de.inetsoftware</groupId>
  <artifactId>jlessc</artifactId>
  <version>RELEASE</version>
</dependency>

I have replaced all

@import ‘xxx’;

with 

@import “xxx”;

 (double quotes instead of single quotes) and now it’s working fine.

Just thought i’d mention this small issue.

Wouter

**Comment by Horcrux7** [comment]
OK, this was fixed in https://github.com/i-net-software/jlessc/commit/434aee29d833da969ebe46b84d91954aea560e9c and is not part of the current public release now. The next version will be available shortly.

**Comment by woutersamaey** [comment]
Great! Thanks!

Wouter
