### ISSUE TITLE
less v2.x

### ISSUE THREAD

**Issue by fredfortier** [i-net-software/jlessc#12]
Does it work with less 2.x?

**Comment by Horcrux7** [comment]
Which feature of 2.x do you are missing? Do you have a test case that is not working?

**Comment by fredfortier** [comment]
No. I have not tested it yet. But my goal would be to process this Bootstrap theme: https://fezvrasta.github.io/bootstrap-material-design/.

**Comment by Horcrux7** [comment]
Please open a new ticket if you have a specific problem.
