### ISSUE TITLE
!important on a color results in a LessException

### ISSUE THREAD

**Issue by JensGabe** [i-net-software/jlessc#16]
The following fails:
color: #FFFFFF!important;

**Comment by Horcrux7** [comment]
I can reproduce it and will fix this in the next days.

**Comment by njlux** [comment]
Thanks, we have change ur project to compile it with 1.6. Are u interested in publish on github?

**Comment by Horcrux7** [comment]
No, we does not want back to such old Java VM that is EOL since many years. But you are free to checkin it in your fork. This should make the merging easier.

**Comment by njlux** [comment]
Ok thanks

**Comment by njlux** [comment]
Thanks

**Comment by Horcrux7** [comment]
All your issues are fixed and a snapshot is created. Please try it. We want create a new version in the next days.
