### ISSUE TITLE
Color variables change over time for Compressed?

### ISSUE THREAD

**Issue by JensGabe** [i-net-software/jlessc#20]
Having a color variable with a color name, ie 'lightgrey' instead of the color code initially returns the correct "#d3d3d3" value, but after some runs, it starts returning "#9400d3" instead ???

The following unit test fails on my machine (JDK7u79) after approx 2000-5000 runs with the compress formatter...?

``` java
final String less = "@c: lightgrey; .t { color: @c; }";
final URL url = new URL("http://localhost");
for (int i = 0; i < 20000; i++)
{
    assertEquals(Integer.toString(i), ".t {\n  color: lightgrey;\n}\n", Less.compile(url, less, false));
}
for (int i = 0; i < 20000; i++)
{
    assertEquals(Integer.toString(i), ".t{color:#d3d3d3}", Less.compile(url, less, true));
}
```

I have tried to debug, but it appears as if either native Double.longBitsToDouble or Double.doubleToRawLongBits somehow suddenly returns a new value for the same expression?
I know this is does not appear to be a JLessC issue directly, but can you verify the issue, and somehow bypass it?

**Comment by Horcrux7** [comment]
I can reproduce it with Java 7u40 on windows. It work with Java 8 and ikvm. This sounds like a JIT error. Because Java 7 is EOL it make no sense to report it as bug.

I have no idea how to fix it without completely rewritting.

**Comment by Horcrux7** [comment]
I found an equals problem http://stackoverflow.com/questions/6371965/final-non-canonical-nan-double-value-changes-during-runtime

Trying to use strictfp show that the problem is Double.longBitsToDouble. But it solve not the problem. It change only the value.

**Comment by Horcrux7** [comment]
Fix with https://github.com/i-net-software/jlessc/commit/9b41a1b47f1a7c9c9d0b5f46f5a02b6ea0c0485f
