### ISSUE TITLE
@import Ausdrücke innerhalb von Blöcken - weitere issues

### ISSUE THREAD

**Issue by konfusio** [i-net-software/jlessc#24]
Hallo :)

nach dem ersten Fix sehe ich nun folgende Probleme:
es wird aus der importierten Datei nur der erste Ausdruck geparsed/ins css übernommen.

folgendes Beispiel:

```
#baufilead_fancybox .baufilead_dialog {
    @import "dialog-tags.less";
}
```

dialog-tags.less:

```
form {
    .defaultAttributes();
    background-color: transparent;
}
img {
    .defaultAttributes();
}
```

im css sehe ich nur 
`baufilead_fancybox .baufilead_dialog form` 
es fehlt 
`baufilead_fancybox .baufilead_dialog img` 

VG
Steffen

**Comment by konfusio** [comment]
prima, jetzt klappts.
Die Generierungszeit verbessert sich bei uns dadurch von 554 Sekunden mit lesscss-java
auf 378 Sekunden.
Zur Info, wir generieren etwas über 2000 CSS Dateien.
Dabei werden 22 umfangreiche less Dateien stets wiederverwendet.
Die 2000 anderen less Dateien definieren im wesentlichen die Werte der Variablen und ergänzen/überschreiben die Regeln.
Vielleicht könnte man die Zeit noch weiter drücken, wenn man das Parsen nur einmal macht?
Das stelle ich mir aber auch nicht ganz trivial vor ;)

**Comment by Horcrux7** [comment]
Es sollte noch eine Menge Luft drin sein. Für uns Bestand bisher kein Bedarf. Das Parsen zu cachen dürfte sehr gefährlich sein und wenig bringen. Wenn du mir eine Probe schicken kannst, könnte ich es profilen. Du kennst ja meine Adresse.

**Comment by Horcrux7** [comment]
Hi Stefan,

Mit dem letzten Fix und einer eigenen ReaderFactory sollten noch mal ca. 30% Speed drin sein.

```
     ReaderFactory factory = new ReaderFactory() {
        private HashMap<URL, String> cache = new HashMap<>();

        @Override
        Reader create( URL url ) throws IOException {
            String str = cache.get( url );
            if( str == null ) {
                str = new Scanner(url.openStream(), "UTF-8").useDelimiter("\\A").next();
                cache.put( url, str );
            }
            return new StringReader( str );
        }
    };
```

**Comment by gamma** [comment]
I know that you guys are from Germany but please try to post issues and comments in english so that  international visitors know what is going on an can find potential fixes for their problems.  Especially for helpful code snippets like this: please comment in english.
