### ISSUE TITLE
Missed semicolon when 2 equal selectors follow each other

### ISSUE THREAD

**Issue by olegcherr** [i-net-software/jlessc#27]
Try to compile the code below using compression:

```
body { color: #fff; }
body { background: #fff; }
```

The output would be:

```
body{color:#fffbackground:#fff}
```

As you can see, a semicolon is missed.

This case with the same selectors following each other occurs pretty often if you actively use `@imports`. For example, you include a "parent" file with common styles, and then override some of them in the "child" file.

Anyway... Thanks for the amazing compiler!

**Comment by Horcrux7** [comment]
I can reproduce it and work on it.

**Comment by Horcrux7** [comment]
I have fix it and upload a snapshot version to https://oss.sonatype.org/content/repositories/snapshots/
