### ISSUE TITLE
Duplicates of css-rules appear when including the same file several times

### ISSUE THREAD

**Issue by olegcherr** [i-net-software/jlessc#28]
Let's assume we have 2 files:

**fileA.less:**

```
.classA {
    width: 100%;
}
```

**fileB.less:**

```
@import "fileA";
@import "fileA";
@import "fileA";
```

The output would be:

```
.classA{width:100%;width:100%;width:100%}
```

~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

**_That was a pretty strange use case, so below I'm going to show you the real case._**

**main.less:**

```
@import "helpers";
@import "sitePart1";
@import "sitePart2";
```

**helpers.less:**

```
.box-sizing(@val) {
    -moz-box-sizing: @val;
    -webkit-box-sizing: @val;
    box-sizing: @val;
}
```

**sitePart1.less:**

```
@import "helpers";

textarea {
    .box-sizing(border-box);
}
```

**sitePart2.less:**

```
@import "helpers";

// other styles
```

The output:

```
textarea{
-moz-box-sizing:border-box;-webkit-box-sizing:border-box;box-sizing:border-box;
-moz-box-sizing:border-box;-webkit-box-sizing:border-box;box-sizing:border-box}
```

~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

This issue hurts the performance of the web-page a lot.
A ton of duplicates is being loaded in css files.
The only workaround by now - is **not** to include `helpers.less` in every file, but you know... As Intellij IDEA says, it's a good practice to import dependencies explicitly in every particular place where they are needed.

**Comment by Horcrux7** [comment]
Yes, this is once of the open TODOs. I will look into now.

**Comment by Horcrux7** [comment]
I have implements it and create a snapshot. Please test it.
