### ISSUE TITLE
Mixins with Multiple Parameters – dummy semicolon doesn't work

### ISSUE THREAD

**Issue by olegcherr** [i-net-software/jlessc#33]
Accordint to the [lesscss documentation](http://lesscss.org/features/#mixins-parametric-feature-mixins-with-multiple-parameters) we can use dummy semicolon to create mixin call with one argument containing comma separated css list: `.name(1, 2, 3;)`

Unfortunately this doesn't work in jlessc:
```
.transition(@val) {
	-moz-transition: @val;
	-webkit-transition: @val;
	-o-transition: @val;
	transition: @val;
}

div {
	.transition(color 1s, opacity 2s;); // Error
}
```

It would be very convenient.
And thank you for your job!

**Comment by Horcrux7** [comment]
You can try the snapshot if this solve your problem.

**Comment by olegcherr** [comment]
Perfect! Thanks!
