### ISSUE TITLE
error positions in LessExceptions should be machine-friendly

### ISSUE THREAD

**Issue by ritschwumm** [i-net-software/jlessc#36]
i'd like to use the filename, line and column of an error in my sbt build -
right now the only way to get at them is parsing the String that comes out of getMessage.

i'll open a PR as soon as #35 is solved.

**Comment by Horcrux7** [comment]
You thing on some things like the follow?

`public List<LessStackTraceElement> getLessStackTrace();`

```
public class LessStackTraceElement {
  public String getFileName();
  public int getLineNumber();
  public int getCoumnNumber();
}
```

**Comment by ritschwumm** [comment]
yes, something like this:
https://github.com/i-net-software/jlessc/compare/master...ritschwumm:wip/pos
