### ISSUE TITLE
can't this not be build like a osgi/eclipse plugin jar?

### ISSUE THREAD

**Issue by jcompagner** [i-net-software/jlessc#49]
The manifest of the jar (1.6 release on maven central) is kind off completely empty
Can this not be exported like an eclipse plugin/osgi enabled jar?
so it can be better used in those environments?

as an example of an apache project that does this:
https://mvnrepository.com/artifact/commons-io/commons-io/2.6

so having a Bundle-SymbolicName: entry (i guess: de.inetsoftware.jlessc)

Export-Package: xxx and Bundle-Name: xxx

and i think for the latest java releases also
Automatic-Module-Name: same as symbolic name

that way i can just very quickly use it in an eclipse based project or any other osgi based project

**Comment by Horcrux7** [comment]
Because JLessC is not a OSGI bundle there is no sense to add OSGI bundle properties. We can use the current jar file without any problems in Eclipse projects.

I am not familiar with OSGI but if it help you then we can add some properties to the manifest. If I understand you then you want the follow 3 lines added:

```
Bundle-SymbolicName: de.inetsoftware.jlessc
Export-Package: com.inet.lib.less
Automatic-Module-Name: de.inetsoftware.jlessc
```
Is this all?

**Comment by jcompagner** [comment]
yes and also i think Bundle-Version to reflect your release version
but you use gradle to build right? then i think adding a bit to the config files:

https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md

will do this all for you (the Create a task of the Bundle type section)

**Comment by Horcrux7** [comment]
Please can you check if the snapshot solve your problem?
https://oss.sonatype.org/content/repositories/snapshots/de/inetsoftware/jlessc/1.7-SNAPSHOT/

**Comment by jcompagner** [comment]
i finally could test this and it seems to work fine i could generate a eclipse p2 update site with it (and use it really in an eclipse plugin)
