### ISSUE TITLE
Make it available through Maven

### ISSUE THREAD

**Issue by joain946** [i-net-software/jlessc#5]
If this library would be available through Maven (http://search.maven.org/) it would simplify things a lot.

**Comment by codler** [comment]
+1

**Comment by Horcrux7** [comment]
We are working to make it available through Maven with the next release. This will need 1-2 weeks.

**Comment by Horcrux7** [comment]
Finish! You can access version 1.1 in the maven central with:

```
    <dependency>
      <groupId>de.inetsoftware</groupId>
      <artifactId>jlessc</artifactId>
      <version>RELEASE</version>
    </dependency>
```

**Comment by codler** [comment]
Awesome thanks @Horcrux7!, I just wonder was it intentional or accident to name it `de.inetsofware` instead of `de.inetsoftware`?

**Comment by Horcrux7** [comment]
Thanks for the tip. We have not see it. A spelling mistake and a large count of copy and paste. We will restart the process and correct this.

**Comment by Horcrux7** [comment]
Finish with the second try. Now it is de.inetsoftware.

**Comment by codler** [comment]
:+1:
