### ISSUE TITLE
url(image.png) or url('image.png') urls in a nested (imported less file) are not rewritten.

### ISSUE THREAD

**Issue by jcompagner** [i-net-software/jlessc#54]
There was code already in FunctionExpression.appendTo
but large part was commented out..
I uncommented parts of it again and changed the way a bit to get to a normalized url (using the URI class)
The case of the url looks now like this:

`
   case "url":
                    String url = get( 1 ).stringValue( formatter );
                    boolean quote = false;
                    char quoteChar = 0;
                   if (new URI(url).getScheme() == null) {
	                    if( url.length() >= 2 ) {
	                        quoteChar = url.charAt( 0 );
	                        if( quoteChar == '\'' || quoteChar == '\"' ) {
	                            if( url.charAt( url.length() - 1 ) == quoteChar ) {
	                                url = url.substring( 1, url.length() - 1 );
	                                quote = true;
	                            }
	                        }
	                    }
	                    String baseUrl1 = get( 0 ).stringValue( formatter );
	                    url= new URI(baseUrl1.substring(0, baseUrl1.lastIndexOf('/')+1) + url).normalize().toString();
                   }

                    formatter.append( "url(" );
                    if( quote ) {
                        formatter.append( quoteChar );
                    }
                    formatter.append( url );
                    if( quote ) {
                        formatter.append( quoteChar );
                    }
                    formatter.append( ")" );
                    return;
`

so i test if the url already has a scheme or not, if if has then it does what it did until now.
If it doesn't have a scheme i strip the qoutes and remember them (the commented code)
and make a URI from the base with the url, normalize it and then use the toString()

**Comment by jcompagner** [comment]
also looked at the data-uri for the same problem.
First in LessParser.parseExpression i hanged the relativeUrl.toString() to relativeUrl.getPath()

`    case "data-uri":
                        case "colorize-image":
                            Operation op = parseParameterList();
                            op.addLeftOperand( new ValueExpression( reader, relativeURL.getPath() ) );
                            right = new FunctionExpression( reader, str, op );
                            break;
`
this is because later on in UrlUtils.dataUri method we do:

 URL url = new URL( formatter.getBaseURL(), relativeURL );

there that same url is really seen as relative and not as file:/somepath
and that is then added to the getBaseUrl() which can also be something with a scheme (http or file)

besides that in that same method i added one line of code:
        url = new URL( url, urlStr );
        urlStr = url.getPath().substring(1);

so that the urlStr is suddenly the complete path from the baseUrl (the same fix as in the url() so that it rewrites to the right base url) 
That is then used when it can't open the stream or it is to big and the image is not inlined.

**Comment by Horcrux7** [comment]
URL handling is very complex and not 100% determinist. Do you have a sample for your problem?

**Comment by jcompagner** [comment]
[less.zip](https://github.com/i-net-software/jlessc/files/2932747/less.zip)


here a sample, you start with the main.less that is the root.
that goes into a subfolder that has a less, that includes again a less from a sub folder from there
and that less file has a image that is included with ../

the result should be that the image is in the main.css as subfolder/whatsapp.png
so that it really works (seen from the main.css)

i added als a data-uri example and also a full http example that last one should be left alone

**Comment by jcompagner** [comment]
maybe the data-uri example can als also be enhanced so the picture that we include is bigger then the threshold that it will inline it..
Because then it should work just as the normal url()

**Comment by Horcrux7** [comment]
I have run the sample and the result is like I expected. Like lessc it also produced.

```
.mylabel {
  background-image: url('../whatsapp.png');
}
.mylabel2 {
  background-image: url("data:image/png;base64,.....");
}
.mylabel3 {
  background-image: url('http://lesscss.org/public/img/less_logo.png');
}
```
If you expected that the relative urls will be converted to an absolute URL?

**Comment by jcompagner** [comment]
this one:

.mylabel {
  background-image: url('../whatsapp.png');
}

is incorrect
that will not work..
because i parse the main.less to main.css

so the browser gets when i serve that main.css on the url like:

localhost/main.css

then in the main.css i have the above url ('../whatsapp.png') so the browser will never find that.
The url should be relative to the main.css...
because the whatsapp.png is in the dir:

localhost/subfolder/whatsapp.png
so the end result should be:

.mylabel {
  background-image: url('subfolder/whatsapp.png');
}

then the browser will find this just fine..

But i have to say, this url rewrite is an option in less.js (-rw option)
that is default also false, what in my eyes is very weird.. That should be default true, you always want to rewrite the urls..

For example my less.zip rename all the .less files to plain.css files itself 
so we now use plain css import in the browser 
then main.css will work fine:
the browser will load localhost/main.css
that does an import to localhost/subfolder/sub.less
that sub.less does an import to  localhost/subfolder/sub/sub.less
then the browser encounters:

.mylabel {
	background-image: url('../whatsapp.png'); 
}

and i searches relative to localhost/subfolder/sub/sub.less to ../whatsapp.png and it loads it from:
localhost/subfolder/whatsapp.png

so that is how you should do it in plain css. So i want to keep that same behavior also when using less. (even if less would import a css right into the less)

The sub.less nested in subfolder/sub/ should not "know" that the root is really just / where it is included..
I could also have a main2.less
that also includes /subfolder/sub/sub.less 
but main2.less is not on the root now that is in localhost/main2/main2.less

then it gets a bit more complex i have to say.....
because then what you really want is that the url that is still in less.less: background-image: url('../whatsapp.png'); should become: background-image: url('../subfolder/whatsapp.png'); 

so it it is accessible from main2/main2.less ...
of course we could generate stuff like: url('/subfolder/whatsapp.png'); 
that kind of works when it is just on localhost/ (or the base html tag is set in the index page)
but that could break in some scenario's....

**Comment by Horcrux7** [comment]
```
But i have to say, this url rewrite is an option in less.js (-rw option)
that is default also false, what in my eyes is very weird.. That should be default true, you always want to rewrite the urls..
```
Do you means the option `-ru`. For example `-ru=all`

We can not change the default behavior because this can break to many. But we can add an option. In the class Less we can add:
```
String compile( URL baseURL, String lessData, Map<String,String> params, ReaderFactory readerFactory )
```

**Comment by jcompagner** [comment]
Ahh yes that could be.. yes I always enable that property (in my eyes that should be default, without it it should break a lot in my eyes)

But I am fine with having a property support just like less.js

I wonder how do you do this or don't you really used this nested less files with nested images?

Also I wonder how then data-uri works how do you interpreted that url then? Because in the end that's the same thing.. why did that data-uri example work?? Because there we do exactly what I describe above right to generate the correct url to get the input stream..

**Comment by Horcrux7** [comment]
> But I am fine with having a property support just like less.js

Ok, I will try it. It can take some time.

> I wonder how do you do this or don't you really used this nested less files with nested images?

I need to analyze it and try to implements it first before I can say how this will work.

> Also I wonder how then data-uri works how do you interpreted that url then?

There seems currently an inconsistency. I need to see how we have use this currently. But it should be like the url function.

**Comment by jcompagner** [comment]
> > I wonder how do you do this or don't you really used this nested less files with nested images?
> 
> I need to analyze it and try to implements it first before I can say how this will work.

I didn't mean how it should work in JLessc but how are you now really using it in real live 
(so where you use JLesc now with)

 
> > Also I wonder how then data-uri works how do you interpreted that url then?
> 
> There seems currently an inconsistency. I need to see how we have use this currently. But it should be like the url function.

And thats the thing

we have @import statements that are handles through the reader but really are i think always relative to the current doc
Then we have url('x') and data-uri('y')

and data-uri can just become a url or it should be inlined and if it is inlined it is loaded from disk somehow.
And that loading from disk, should be the same as handling imports... because imports also can work just fine if you are in a subfolder and you do ../some.less in the import..

So that stuff already works with the "base url"  + "relative url" + "url_import_part"

i think url/data-uri should work all the same to get to that.

And that is why i say that i find it really weird that urls are not rewritten by default because you are changing the base if you import stuff... So it should just be added, same for data-uri that are converted to just url('name') (because of the size)

**Comment by Horcrux7** [comment]
I have implements the behavior of the option "rewrite-urls" like of Less CSS. I find the behavior party curious. But this is the standard.

If you think that the behavior of Less CSS is wrong then we are the wrong address. Then you need contact the original project.

To answer your question to "data-uri". We does not use it. We use only "colorize-image".

**Comment by jcompagner** [comment]
This is not fully working like i expect, but not sure which variant should be fixed..

"all" also makes these:

background-image: url('http://www.clker.com/cliparts/3/m/v/Y/E/V/small-red-apple-md.png');

like

background-image: url('/cliparts/3/m/v/Y/E/V/small-red-apple-md.png');

so thats not what i want, so if i use "local" then the above is correct but then this:

background-image: url('whatsapp.png');

is not converted to:

background-image: url('test/whatsapp.png');

because the main less file is on the parent dir (and that background is in a sub dir less file)

So the question is what is local? I don't want to be forced to use ./whatsapp.png thats also what i wouldn't do in plain css.

For me local is everything that doesn't start with a protocol (so http for the most part)

But i guess if i do "all" then also stuff that are already full urls shouldn't really be touched...

**Comment by jcompagner** [comment]
ok i checked this with lessc compiler

the "local" is fine that behaves exactly the same between the 2 compilers

but "all" is different, with "all" the http url is still not touched and the rest is
So if i test that:

  boolean isRewriteUrl( String url ) {
        switch( rewriteUrl ) {
            default:
            case 0:
                return false;
            case 1:
                return url.startsWith( "." );
            case 2:
			try {
				return new URI(url).getScheme() == null;
			} catch (URISyntaxException e) {
				return false;
			}
        }
    }

then it works, so try to parse it and only rewrite it all when there is no scheme, and i guess when the parsing fails then also don't try to rewrite it... very likely invalid anyway

**Comment by jcompagner** [comment]
can the data-uri stuff not really do the same as other urls? (imports of less files or url rewrites?)

it would be nice if we could do this:

 static void dataUri( CssFormatter formatter, String relativeUrlStr, final String urlString, String type ) throws IOException {
        URL url = formatter.getBaseURL();
        String urlStr = removeQuote( urlString );
        url = new URL( url, urlStr );
        if( formatter.isRewriteUrl( urlStr ) ) {
        	 url = new URL( new URL( formatter.getBaseURL(), relativeUrlStr ), urlStr );
        }

so i added that last if () just like for urls that are rewritten

i know you added in the catch:

  } catch( Exception e ) {
                // try rewrite location independent of option "rewrite-urls" for backward compatibility, this is not 100% compatible with Less CSS
                url = new URL( new URL( formatter.getBaseURL(), relativeUrlStr ), urlStr );
                input = formatter.getReaderFactory().openStream( url );
            }

but that is a bit annoying for me, because for all data-uri that are in sub folders it will always go in there and that will the resolve it..
So it would be nice if rewrite property is directly used so i don't get all the time first a illegal call

**Comment by Horcrux7** [comment]
Do you have a solution that not break the tests? The current quirky implementation make the JUnit tests green.

On the other hand it use the default behavior of Less CSS first. This is faster for the most users.

The resolving of an URL or two ist fast compared to the processing of the image later. If the call of openstream() on an not existing file is a performance problem then you should optimize this with the ReaderFactory. 

Please can you describe your use case a little more that I can understand it? Which type of URL do you use that are such slow? It sounds also that you process a large count of images. This would result in a large CSS file. How many images do you process and how large is your output?

**Comment by jcompagner** [comment]
oh sorry, it is not slow, but annoying for us because in the ReaderFactory when i need to resolve something through any of the calls (data-uri or imports) and i don't find it i will report this to our users.. To let them know they are using something wrong because the thing that they ask for is not found
Problem is that in the current impl i first always get one that is bad (if a sub folder is used)


I made a test with lessc itself, to do some testing, and by default this is just weird (if i don't give any params like url rewrite). The sample:

parent.less:
@import 'test/sub.less';

then in test/sub.less:
@import 'test.less';

and that test/test.less:
.my1 {
	background-image: url('whatsapp.png');
}
.my2 {
	background-image: data-uri('whatsapp.png');
}
.my3 {
	background-image: url('http://www.clker.com/cliparts/3/m/v/Y/E/V/small-red-apple-md.png');
}

now if i do just in the parent dir:

lessc parent.less

the output is:
Skipped data-uri embedding of whatsapp.png because file not found
Skipped data-uri embedding of whatsapp.png because file not found
.my1 {
  background-image: url('whatsapp.png');
}
.my2 {
  background-image: url('whatsapp.png');
}
.my2 {
  background-image: url('http://www.clker.com/cliparts/3/m/v/Y/E/V/small-red-apple-md.png');
}

that output is in my eyes completely weird, Why can less find the import to test.less (from sub.less) in that subdir but it can't find the data-uri which is exactly the same as the import....
But besides that the generated parent.css will never resolve the url of whatsapp.png.. (that sits in the test sub dir)

so what i do now is:

lessc -ru=local parent.less

now the weird part.. now it suddenly doesn't complain about the data-uri, now it suddenly can find it..
.my1 {
  background-image: url('whatsapp.png');
}
.my2 {
  background-image: url("data:image/png;base64,iVBxxxxxxxxx");
}
.my2 {
  background-image: url('http://www.clker.com/cliparts/3/m/v/Y/E/V/small-red-apple-md.png');
}
 
so local url rewrite suddenly fixes the data-uri problem but i have no idea why.. Because it is not what they see as local (starting with ./)

then i use:
lessc -ru=all  parent.less

now everything is fine
.my1 {
  background-image: url('test/whatsapp.png');
}
.my2 {
  background-image: url("data:image/png;base64,iVBxxxxxxxxx");
}
.my2 {
  background-image: url('http://www.clker.com/cliparts/3/m/v/Y/E/V/small-red-apple-md.png');
}

now that parent.css file that is generated is  really fully working..

But anyway lessc seems to be really doing something different when rewrite is used..
Personally i don't mind that weird local variant that suddenly data-uri are resolved but it would be nice that in the "all" mode it does work (like my patch)
