### ISSUE TITLE
Incorrect variable resolution in calc() operation when using minification

### ISSUE THREAD

**Issue by jmesny** [i-net-software/jlessc#64]
Hi.

When compiling a Less string using minification, variables having a 0 value have their units stripped.
When such a variable is used in a `calc()` operation, this leads to an incorrect property that the browser will ignore.

Here is a test that highlight the issue:

```
@Test
void shouldProperlyCompileLessString() {
    String less = "@variable: 0px; .element{ width: calc(2em + 0px); height: calc(2em + @{variable}) }";

    String result1 = Less.compile(null, less, false);

    // When not minified, result is ok
    assertThat(result1).isEqualToIgnoringWhitespace(".element{ width: calc(2em + 0px); height: calc(2em + 0px); }"); // ✅

    String result2 = Less.compile(null, less, true);

    // When minified, variable resolution leads to a missing unit in a calc operation
    assertThat(result2).isEqualToIgnoringWhitespace(".element{ width: calc(2em + 0px); height: calc(2em + 0px) }"); // ❌
    
    // ==> Actually, result2 is equal to `.element{width:calc(2em + 0px);height:calc(2em + 0)}`
}
```

Thanks!

**Comment by Horcrux7** [comment]
- First you need to use outside of a string the syntax without curly braces.
  `@variable: 0px; .element{ width: calc(2em + 0px); height: calc(2em + @variable) }`

- Then this is the standard behavior of compress mode. It remove the unit if the value is zero. This is like the original lesscss. If we change this then this is not compatible with lesscss. You should first open a bug report there.

> this leads to an incorrect property that the browser will ignore.

Is this for all browser or only for one?
