### ISSUE TITLE
:extend() not working with elements

### ISSUE THREAD

**Issue by tofi86** [i-net-software/jlessc#67]
Hi, I'm currently switching over from https://github.com/marceloverdijk/lesscss-java to your less compiler and had pretty good results so far.

However, I stumbled upon an issue which the old compiler solved without a problem:

The [`:extend()`](http://lesscss.org/features/#extend-feature) feature does not seem to work with elements as a parameter value:

```less
h1 {
	font-size: 20px;
}
h2 {
	&:extend(h1);
}
```

This throws an error message:

```
Undefined mixin: &:extend
 	 on line 1320, column 14
 	 on line 1318, column 24
```

The examples in the Less docs state, that extending an element selector is supported.

It works fine though with a class selector: `&:extend(.heading1);`

Any chance to get this fixed?

Thanks :-)

**Comment by Horcrux7** [comment]
I have create a snapshot version that you can test it.

**Comment by tofi86** [comment]
Awesome! I built `1.9-SNAPSHOT` locally and it works perfect! Thanks for the quick fix!

Do you have an ETA for the next stable release?
