### ISSUE TITLE
:extend() syntax not working as expected for referenced Imports

### ISSUE THREAD

**Issue by gamma** [i-net-software/jlessc#71]
Consider the following two files:

_root.css_

    @import (reference) "import.less";
    .c {
        content: 'c';
    }

_import.css_

    .a {
      content: 'a';
    }
    .b:extend( .a ) {
      content: 'b';
    };

The expected out put, due to the *reference* (as per the less compiler) is:

    .c {
        content: 'c';
    }

But the *wrongly* output css ist:

    .b {
      content: 'a';
    }
    .c {
      content: 'c';
    }

**Comment by Horcrux7** [comment]
It look like that the behavior has changed in newer versions. This was correct in older versions.
