### ISSUE TITLE
Custom Function Interface

### ISSUE THREAD

**Issue by gamma** [i-net-software/jlessc#72]
Please create an interface that allows registration of custom functions. I'd need a name to be registered and a function, taking the formatter and a list of given expressions.

**Comment by gamma** [comment]
Great. Is it on purpose, that `CssFormatter` and `Expression` are package visible only?

**Comment by Horcrux7** [comment]
There was no requirement for public access until now.

**Comment by SimonFliegel** [comment]
This might be a silly question but can this be used to pass in data to the less file from java such as defining a variable based on used platform?
