### ISSUE TITLE
url rewrite (local or all) options i think should be 1 option

### ISSUE THREAD

**Issue by jcompagner** [i-net-software/jlessc#73]
currently we do in CssFormatter.isRewriteUrl

    boolean isRewriteUrl( String url ) {
        switch( rewriteUrl ) {
            default:
            case 0:
                return false;
            case 1:
                return url.startsWith( "." );
            case 2:
                return !url.startsWith( "data:" ); // data: URL never rewrite
        }
    }

that that is just tricky, for us none of the options work for all of the things we want.
the example we have:

root.less
@import 'subfolder/child.less';

child.less:
.test-image {
	background-image: url('https://servoy.com/wp-content/themes/servoy/images/logo-servoy.png');
}

.test-image2 {
	background-image: url('media/logo-servoy.webp');
}

has 2 things 
1> a background image with a url that is completely from a different site 
2> an media that is again in a subfolder, so seen from the root it is '/subfolder/media/logo-servoy.webp'

not rewriting the urls at all doesn't work because less compiler will make 1 one big css file.
starting from the root.

the problem is if i use "all"
then the first one bombs out because i think this is stripped: https://servoy.com/ so it becomes local:
/wp-content/themes/servoy/images/logo-servoy.png

and will not be found

the second one is correct then that becomes

'subfolder/media/logo-servoy.webp'

but if i then do instead of "all" "local"

then the first one starts working because it is not touched
but then the second one fails.

that becomes

'media/logo-servoy.webp'

and the css file doesn't start there.

I am not sure how people are using "all" at the moment because then only full urls that are given from your own site are kind of working but we strip just some stuff does that have any meaning?

i always had "all" but instead of doing

 return !url.startsWith( "data:" ); // data: URL never rewrite

i had a patched version:
			try {
				return new URI(url).getScheme() == null;
			} catch (Exception e) {
				return true;
			}

so don't do only data: but all with a scheme ...

but it is a bit weird for the "all" todo that

i think it is better to fix "local" and have a right local fix (that is the above one)
so the full code would the be:

  boolean isRewriteUrl( String url ) {
        switch( rewriteUrl ) {
            default:
            case 0:
                return false;
            case 1:
    			try {
    				return new URI(url).getScheme() == null;
    			} catch (Exception e) {
    				return false;
    			}
            case 2:
            	return !url.startsWith( "data:" ); // data: URL never rewrite
        }
    }

so that the "isLocal" check is there that. all uri's that don't have a scheme are assumed to be local the rest aren't and aren't touched.

**Comment by jcompagner** [comment]
What i mean with should be one option is that i think rewrite urls is kind of a boolean

"no"
"yes (all local urls)"

**Comment by Horcrux7** [comment]
```
case 1:
try {
    return new URI(url).getScheme() == null;
} catch (Exception e) {
return false;
```
This would result in a different behavior to the documentation of the property `rewrite-urls`. 
```
Rewrites URLs to make them relative to the base less file. 'all' rewrites all URLs, 'local' just those starting with a '.', 'off' simple inline it.
```
Another problem is that it also will rewrite the data protocol.

I think a new option value is a better solution. If you make a pull request for a new option then split it from the extended handling for inline images. This will it make easier to check it.

**Comment by jcompagner** [comment]
in my eyes that documentation should be fixed then
because local urls are not just urls starting with a . 

who does that? i don't see that in css or less files at all around me
everybody just assumes that the (local) files are files based from the css or less file that they are in.

so in a less/css file we have

    url1: url('image.jpg'); 
    url3: url('subfolder2/image.jpg'); 

(just like in the rewrite test files)

i don't think it will rewrite the data protocol because the scheme is "data" 

you can see that in the rewrite test:
 sub1.less

  url5: url("data:image/jpeg;base64,bm90IGFjdHVhbGx5IGEganBlZyBmaWxlCg==");

the local one just keeps it like that as is.

**Comment by Horcrux7** [comment]
> in my eyes that documentation should be fixed then
> because local urls are not just urls starting with a .
>
> who does that? i don't see that in css or less files at all around me
> everybody just assumes that the (local) files are files based from the css or less file that they are in.

Take a look in the documentation of  LessC http://lesscss.org/usage/#less-options-rewrite-urls
You can discuss this with the maintainer of LessC.

> i don't think it will rewrite the data protocol because the scheme is "data"

This depends of a data: URL handler is registered in the Java VM or not. By default it is not the case and it will use the fallback. Such side effect should not occur in a library.

**Comment by jcompagner** [comment]
> Take a look in the documentation of LessC http://lesscss.org/usage/#less-options-rewrite-urls

ahh so we should patch "all" not local that seems to be special
They don't mention what "all" really means if the urls are already with a scheme (data: http: https:) (because those can't be adjusted they are already full urls)

then i will adjust my patch to not patch "local" but "all"

> This depends of a data: URL handler is registered in the Java VM or not. By default it is not the case and it will use the fallback. Such side effect should not occur in a library.

no this is not the case: this is URI$Parser code:


      // [<scheme>:]<scheme-specific-part>[#<fragment>]
        //
        void parse(boolean rsa) throws URISyntaxException {
            requireServerAuthority = rsa;
            int ssp;                    // Start of scheme-specific part
            int n = input.length();
            int p = scan(0, n, "/?#", ":");
            if ((p >= 0) && at(p, n, ':')) {
                if (p == 0)
                    failExpecting("scheme name", 0);
                checkChar(0, L_ALPHA, H_ALPHA, "scheme name");
                checkChars(1, p, L_SCHEME, H_SCHEME, "scheme name");
                scheme = substring(0, p);

as you can see it has nothing todo with registered stuff or not
a scheme is really how the url is build up. 

So if the url has a :  (before a ? / or # char) then anything before it is the scheme

**Comment by jcompagner** [comment]
just to be clear what i am talking about:

http://lesscss.org/usage/#less-options-rewrite-urls

in those examples what they talk about

"none" or "local" will just end up in an invalid css file...

because "main.css" that includes "/global/font.less" will have

src: url('myfont/myfont.woff2') format('woff2');

which shouldn't be correct because "myfont" should not be a subdirectory of the "root" but a subdirectory of "global"

Else if that wasn't the case then the stand alone "font.less" if we would compile that and serve to a browser would also create:

src: url('myfont/myfont.woff2') format('woff2');

but the browser would see that in a subdir where font.less is in that url would then be

/global/font.css

so the browser would expect to see 

/global/myfont/myfont.woff2

thats how our system at least work everything is "local" or related to each other you design a less file and everything a less file targets through urls is related to its own location.

Any thing else is just weird in my eyes, if you expect that in the above example that "myfont" is in the root
then the font.less by itself is just invalid, that can never be used as its own, it kind of knows that it is included in the main only and that from the main on you can find it again.
And it can never be included into something else, reused again, like not the /main.less but now i have /something/main2.less 
that imports:

@import "../global/fonts.less";

where should then the "myfont" be looked at?

as a real world example:

/theme1/main.less
/theme2/main.less

both import something common

@import "../global/fonts.less";

that font has 

@font-face {
  font-family: 'MyFont';
  src: url('myfont/myfont.woff2') format('woff2');
}

then i just expect that the woff2 is in:

/global/myfont/myfont.woff2


so both main generated css files should in the end, end up in

@font-face {
  font-family: 'MyFont';
  src: url('../global/myfont/myfont.woff2') format('woff2');
}

(they are served from there "themeX" dir)

i will also add this scenario as one of the rewrite tests

**Comment by Horcrux7** [comment]
> just to be clear what i am talking about:
> http://lesscss.org/usage/#less-options-rewrite-urls
> in those examples what they talk about
> "none" or "local" will just end up in an invalid css file...

Again it make no sense to discus this here. If you have a sample that work different to the standard implementation then post it. I self never use this feature. The simplest is to write the final URL instead a complex rewrite.

> > This depends of a data: URL handler is registered in the Java VM or not. By default it is not the case and it will use the fallback. Such side effect should not occur in a library.
> 
> no this is not the case: this is URI$Parser code:

The difference is in the code places where isRewriteUrl(String) is used. On this places is worked with a URL and not with a URI.

**Comment by jcompagner** [comment]
> Again it make no sense to discus this here. If you have a sample that work different to the standard implementation then post it. I self never use this feature. The simplest is to write the final URL instead a complex rewrite.

i don't see how this could work in the standard then
i will make some test with the lesscss parser, to really see what is then so different and if they really result in broken css files.


> The difference is in the code places where isRewriteUrl(String) is used. On this places is worked with a URL and not with a URI.


but why would that matter based on the isRewriteUrl?
there i only want to know 1 thing. does it have a scheme or not.
If it has a scheme we already know (like the current data: check in "all" mode)
we should not rewrite it.

For me that is just the rule, if it has a scheme (http, https, data) then rewriting that url makes no sense, rewrite to what? That very likely means it will end up in a broken url.
It is just exactly the same why you added in the "all" mode that "data:" shouldn't be done..
That check can just be new URI(url).getScheme() == null, for data: this would be also false, and then also for http: or https:
also when an url already starts with / that means it is already targetting the root, so i think also in "all" mode its not valid to rewrite that.

**Comment by jcompagner** [comment]
ok tested the lessc compiler itself with the -ru option (and without)
without and with -ru=local is for us just bogus that generates a invalid css file that won't work

but -ru=all does exactly what i want (and how my patch works with "local")

what i tested:

rootdir/

theme/main.less:
`@import '../global/image.less';`

global/image.less

```
.image {
  background-image: url("image/image.png");
}
.image2 {
  background-image: url("http://test.com");
}
.image3 {
  background-image: url("data:text/plain;base64,SGVsbG8sIFdvcmxkIQ==");
}
.image4 {
  background-image: url("/image.png");
}
```

then the output with local or with nothing is exactly the above, it doesn't touch anything.

but with:

lessc.cmd -ru=all .\theme\mainless.less

```
.image {
  background-image: url("../global/image/image.png");
}
.image2 {
  background-image: url("http://test.com");
}
.image3 {
  background-image: url("data:text/plain;base64,SGVsbG8sIFdvcmxkIQ==");
}
.image4 {
  background-image: url("/image.png");
}
```

thats exactly what i want, the "local" urls are adjusted to the the right path where the image really is (compared to the css file that is generated in the place where the less file is)

and anything with a scheme (http or data) is not touched and also what is already on the root (/) is not touched.

i will adjust my patch so that all my changes map to "all" not "local"

**Comment by Horcrux7** [comment]
Should be fixed.
