### ISSUE TITLE
data-uri rewrite fixes

### ISSUE THREAD

**Issue by jcompagner** [i-net-software/jlessc#74]
this is very related also to: https://github.com/i-net-software/jlessc/issues/73

because the data-uri can have the same thing it can just have 

data-ur('folder/image');

but that folder is not really the root where it all starts (the root.less file that imports it all)
this can be already in one folder deep like in issue 73

So what this patch does is look if normally the url would be rewritted
if so then rewrite the url and then try to load it so where the data gets from will be correct
(it will still fallback if that doesn't work)

besides that this patch also doesn't load in the full data if we notice it will be bigger then 32x1024 (then we inline it anyway)

if we inline it as a normal url (because of a failure loading it or because of it is to big)
then make sure again that we use the rewrite url so the full right url is generated from the root on.

also a small patch to support image/webp formats

**Comment by jcompagner** [comment]
[jlessc.patch.txt](https://github.com/i-net-software/jlessc/files/5617257/jlessc.patch.txt)

**Comment by Horcrux7** [comment]
Should be fixed.
