### ISSUE TITLE
Error by compile less with a non-css/less-color-value

### ISSUE THREAD

**Issue by christingoetz** [i-net-software/jlessc#78]
HEi,

we use your less compiler in our own product. Until now it works fine - thanks a lot for it!

Unfortunatly, now I get this error message 

```
[Fehler] Invalid Color: #Separation
	 on line 2, column 26, file sonderfarbe.less
	 on line 1, column 53, file sonderfarbe.less
	 on line 500, column 20
	 on line 511, column 16
	 on line 510, column 10
	 on line 503, column 4
```

The Problem is `#Separation` in a color-function I have to use for include a specific color. This color function I have to use to use a functionality of a third-party software. (https://www.antennahouse.com/pantone-option)

Two Less-Snipets:

*sonderfarbe.less*
```css
@sonderfarbe: rgb-icc(@ahSeparation, 'PANTONE 185 C');
@ahSeparation: #Separation;
```

*stylesheet.less*
```css
@import "sonderfarbe.less";
...
p {
	color: @sonderfarbe;

}
```

Regards,
Christin

**Comment by Horcrux7** [comment]
How is the definition of `rgb-icc`? 

What is `#Separation`? What is expected here?

**Comment by Horcrux7** [comment]
Look like `#Separation` should be a namespace. Is this right? The new feature Namespace is not supported yet.

**Comment by christingoetz** [comment]
`rgb-icc` is defined as: `rgb-icc(#Separation, 'PANTONE Value')`. However `PANTONE Value` is a varaible value.

I cannnot answer the question:

> What is #Separation? What is expected here?

I need the declaration abbove for a feature of a third-party tool which need this specification for assign Pantone colors in his programm.

(https://www.antennahouse.com/pantone-option)

**Comment by Horcrux7** [comment]
This is the usage of `rgb-icc` and not the definition. It will not help you if I fix the first compiler error and then it is failing inside of `rgb-icc` or produce a wrong result. I need a full sample to fix it. A link to website with a description of a third party tool does not help. Sorry but my time is limited and I does not need this feature.

Alternative you can make a pull request to fix it.

**Comment by Horcrux7** [comment]
Please test a snapshot if this fix the error.

**Comment by sermo-de-arboribus** [comment]
> Look like `#Separation` should be a namespace. Is this right? The new feature Namespace is not supported yet.

Just for the record: The party that defined the rgb-icc() function calls this an "identifier", not a "namespace". Specification is here: https://www.antenna.co.jp/AHF/help/en/ahf-ext.html#rgb-icc

**Comment by sermo-de-arboribus** [comment]
> Please test a snapshot if this fix the error.

We have tested a current snapshot of jlessc and your fix solves our problem. Thank you very much!
